export type XBroadcast = {
  id: string;
  title: string;
  poster: string;
  /** YYYY-MM-DD from the episode key or Master Library date col; "" when unknown. */
  date: string;
};

export type XBroadcastReplay = XBroadcast & {
  hlsUrl: string | null;
};

// ---- GENERATED by `npm run broadcasts:sync` — do not hand-edit ----
export const xBroadcasts: XBroadcast[] = [
  { id: "1DxLdZjlmrQxm", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-09-15" },
  { id: "1DxLdZjQNOaxm", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-09-14" },
  { id: "1NGaroPyqNnJj", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-09-12" },
  { id: "1AKEmvMgaRkKL", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-09-11" },
  { id: "1RKjpbVMRvLJw", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-09-09" },
  { id: "1lKQRWkMVwVGE", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-09-08" },
  { id: "1AxRnZXRdPqxl", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-09-07" },
  { id: "1nxeLMYVXwoJX", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-09-05" },
  { id: "1MJgNbrPzoqGL", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-09-05" },
  { id: "1PKqrNAvXEbGb", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-09-04" },
  { id: "1oKMvNLVMzNGQ", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-09-01" },
  { id: "1kJzDPoaOpRKv", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-08-27" },
  { id: "1oKMvNOXBpnGQ", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-08-26" },
  { id: "1DxleVDmnWgKL", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-08-22" },
  { id: "1jxXgBzgylvJZ", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-08-21" },
  { id: "1OxwbnwmvMoJB", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-08-17" },
  { id: "video-broadcast-2026-08-15-01", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-08-15" },
  { id: "1jxXgBBneeEJZ", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-08-14" },
  { id: "1vKpPNPWnnbKE", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-08-12" },
  { id: "1OxwbnlaZpqJB", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-08-10" },
  { id: "1OGwbbdYvObKB", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-08-07" },
  { id: "1YxNrrlymkVxw", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-08-07" },
  { id: "audio-space-2026-08-05-02", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-08-05" },
  { id: "audio-space-2026-08-05-01", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-08-05" },
  { id: "1kJzDDYMPZXKv", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-08-03" },
  { id: "1pKdRRkyMONJW", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-07-31" },
  { id: "audio-space-2026-07-30-02", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-07-30" },
  { id: "audio-space-2026-07-30-01", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-07-30" },
  { id: "1AKEmmrYnnnKL", title: "CAN'T DUB ME RADIO: ROC SOLID | KAREN CIVIL | WE TURNING UP", poster: "/broadcasts/1AKEmmrYnnnKL.png", date: "2026-07-27" },
  { id: "video-broadcast-2026-07-26-01", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-07-26" },
  { id: "1rGmqqargvLGy", title: "FRIDAY FUNK | THEY STINK WITH MESS | VIBES ONLY", poster: "/broadcasts/1rGmqqargvLGy.jpg", date: "2026-07-24" },
  { id: "1jGXggPZWLVKZ", title: "RORY WAS HATIN | Live Broadcast", poster: "/broadcasts/1jGXggPZWLVKZ.jpg", date: "2026-07-22" },
  { id: "1YGNrrmoqZoGw", title: "STARTING THE WEEK OFF RIGHT PT 2 | TURN UP", poster: "/broadcasts/1YGNrrmoqZoGw.jpg", date: "2026-07-20" },
  { id: "1XxyggRVnEVGM", title: "EXTENDED MESSY LIVE | SPACE WARS & VIBES", poster: "/broadcasts/1XxyggRVnEVGM.jpg", date: "2026-07-18" },
  { id: "1AxRnnwoqwyxl", title: "It's Friday!!!! Whewww Lots to Talk About!!!", poster: "/broadcasts/1AxRnnwoqwyxl.jpg", date: "2026-07-17" },
  { id: "1nxeLLQwQjoJX", title: "MEDIA STREETS ON FIRE!!! LOTS OF FILES", poster: "/broadcasts/1nxeLLQwQjoJX.jpg", date: "2026-07-10" },
  { id: "1dJrPPLmBlqKX", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-07-06" },
  { id: "1DxLddryWQPxm", title: "4TH of July SPECIAL | WAKE IT UP!!!!!", poster: "/broadcasts/1DxLddryWQPxm.jpg", date: "2026-07-04" },
  { id: "1vJpPPOnjPZJE", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-07-03" },
  { id: "1XxyggYqmoeGM", title: "JOE BUDDEN NEW WEBAPP | SATURDAY VIBES | BONUS CONTENT", poster: "/broadcasts/1XxyggYqmoeGM.jpg", date: "2026-06-27" },
  { id: "1qKVmmLLaydxB", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-06-26" },
  { id: "1pKdRRlAvRjJW", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-06-19" },
  { id: "1jGXggZlkdVKZ", title: "NYC | AKADEMIKS SCARED NOW? | JOE BUDDEN VS MOUSE JONES", poster: "/broadcasts/1jGXggZlkdVKZ.jpg", date: "2026-06-15" },
  { id: "1YxNrrOVnryxw", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-06-13" },
  { id: "1PKqrrqvyomGb", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-06-12" },
  { id: "1mGPaawEbrMJN", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-06-02" },
  { id: "1yNGabgjOOdJj", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-02-02" },
  { id: "1gqxvrQPDrexB", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-01-28" },
  { id: "1PlKQOpPnLBJE", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-01-26" },
  { id: "1lPJqvXORAExb", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-01-16" },
  { id: "1OyJAjEEroDxb", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-01-15" },
  { id: "1LyxBXdyVPrGN", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-01-14" },
  { id: "1ZkJzZmNeeWJv", title: "", poster: "/broadcasts/placeholder.svg", date: "2026-01-08" },
  { id: "1MYGNlPQYvvxw", title: "", poster: "/broadcasts/placeholder.svg", date: "2025-12-24" },
  { id: "1zqKVdEyYOLJB", title: "", poster: "/broadcasts/placeholder.svg", date: "2025-12-23" },
  { id: "1ZkKzZkYPlLKv", title: "", poster: "/broadcasts/placeholder.svg", date: "2025-12-16" },
];
// ---- END GENERATED ----

/**
 * Display label for a broadcast. Uses the Broadcast Titles tab title when one
 * exists; otherwise a factual date-based label ("X Broadcast — August 26, 2026")
 * so the page never renders empty headings. This is a descriptor, not a title —
 * real titles still come only from the sheet and blanks still fail the sync.
 */
const MONTH_NAMES = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

export function displayTitleFor(broadcast: XBroadcast): string {
  const real = broadcast.title?.trim();
  if (real) return real;
  const m = broadcast.date?.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (m) {
    const month = MONTH_NAMES[Number(m[2]) - 1] ?? m[2];
    return `X Broadcast — ${month} ${Number(m[3])}, ${m[1]}`;
  }
  return "X Broadcast Replay";
}

export function extractReplayHlsUrl(html: string): string | null {
  const normalized = html
    .replaceAll("\\u0026", "&")
    .replaceAll("\\/", "/")
    .replaceAll("&amp;", "&");
  const matches = normalized.match(/https:\/\/[^"'<>\s]+\.m3u8(?:\?[^"'<>\s]*)?/g) ?? [];
  return matches.find(url => url.includes("periscope-replay") || url.includes("type=replay")) ?? matches[0] ?? null;
}
