export type XBroadcast = {
  id: string;
  title: string;
  poster: string;
  /** YYYY-MM-DD from the episode key or Master Library date col; "" when unknown. */
  date: string;
  /** Verified canonical X broadcast/Space URL; null for archive-only entries. */
  sourceUrl: string | null;
};

export type XBroadcastReplay = XBroadcast & {
  hlsUrl: string | null;
};

// ---- GENERATED by `npm run broadcasts:sync` — do not hand-edit ----
export const xBroadcasts: XBroadcast[] = [
  { id: "1DxLdZjlmrQxm", title: "J1 SPACE DRAMA | IAN DUNLAP INTERVIEW | CREATOR MONETIZATION", poster: "/broadcasts/replay-card.svg", date: "2026-09-15", sourceUrl: "https://x.com/i/broadcasts/1DxLdZjlmrQxm" },
  { id: "1DxLdZjQNOaxm", title: "MONDAY NIGHT SPACE", poster: "/broadcasts/replay-card.svg", date: "2026-09-14", sourceUrl: "https://x.com/i/spaces/1DxLdZjQNOaxm" },
  { id: "1NGaroPyqNnJj", title: "CAN'T DUB ME RADIO: LIL DURK FREE | GLORILLA | ANDRE 3000", poster: "/broadcasts/replay-card.svg", date: "2026-09-12", sourceUrl: "https://x.com/i/broadcasts/1NGaroPyqNnJj" },
  { id: "1AKEmvMgaRkKL", title: "CONSPIRACY TALK | CAMILLE DRAMA | STREET TALK", poster: "/broadcasts/replay-card.svg", date: "2026-09-11", sourceUrl: "https://x.com/i/broadcasts/1AKEmvMgaRkKL" },
  { id: "1RKjpbVMRvLJw", title: "BRIAN SANTIAGO INCIDENT | FAT JOE TOPICS | QUEENS DISRESPECT", poster: "/broadcasts/replay-card.svg", date: "2026-09-09", sourceUrl: "https://x.com/i/spaces/1RKjpbVMRvLJw" },
  { id: "1lKQRWkMVwVGE", title: "DATING TALK | BIRTHDAY PARTY RECAP | KANYE RANKINGS", poster: "/broadcasts/replay-card.svg", date: "2026-09-08", sourceUrl: "https://x.com/i/spaces/1lKQRWkMVwVGE" },
  { id: "1AxRnZXRdPqxl", title: "LABOR DAY LIVE | MARC LAMONT HILL DEBATE | FAT JOE", poster: "/broadcasts/replay-card.svg", date: "2026-09-07", sourceUrl: "https://x.com/i/broadcasts/1AxRnZXRdPqxl" },
  { id: "1nxeLMYVXwoJX", title: "COFFEE RUN: DUMBO | FLEA MARKET VIBES", poster: "/broadcasts/replay-card.svg", date: "2026-09-05", sourceUrl: "https://x.com/i/broadcasts/1nxeLMYVXwoJX" },
  { id: "1MJgNbrPzoqGL", title: "BITCHES LOVE SHRIMP | SPACE TEST", poster: "/broadcasts/replay-card.svg", date: "2026-09-05", sourceUrl: "https://x.com/i/spaces/1MJgNbrPzoqGL" },
  { id: "1PKqrNAvXEbGb", title: "FAT JOE PRESSES JBP | THE N-WORD DEBATE | CLIPPER MONEY", poster: "/broadcasts/replay-card.svg", date: "2026-09-04", sourceUrl: "https://x.com/i/broadcasts/1PKqrNAvXEbGb" },
  { id: "1oKMvNLVMzNGQ", title: "CAN'T DUB ME RADIO", poster: "/broadcasts/replay-card.svg", date: "2026-09-01", sourceUrl: "https://x.com/i/broadcasts/1oKMvNLVMzNGQ" },
  { id: "1kJzDPoaOpRKv", title: "GTA VI REACTION | DRAKE VS FUTURE | AI TAKES JOBS", poster: "/broadcasts/replay-card.svg", date: "2026-08-27", sourceUrl: "https://x.com/i/broadcasts/1kJzDPoaOpRKv" },
  { id: "1oKMvNOXBpnGQ", title: "JBP CHAIN DEBATE | LIL DURK CASE | DUB FREESTYLE", poster: "/broadcasts/replay-card.svg", date: "2026-08-26", sourceUrl: "https://x.com/i/broadcasts/1oKMvNOXBpnGQ" },
  { id: "1DxleVDmnWgKL", title: "GAME VS KENDRICK | MAX B COMEBACK | SWATTING THREATS", poster: "/broadcasts/replay-card.svg", date: "2026-08-22", sourceUrl: "https://x.com/i/broadcasts/1DxleVDmnWgKL" },
  { id: "1jxXgBzgylvJZ", title: "GAME VS THE WEST | TUPAC DOC BACKLASH | RIP P FROM QC", poster: "/broadcasts/replay-card.svg", date: "2026-08-21", sourceUrl: "https://x.com/i/broadcasts/1jxXgBzgylvJZ" },
  { id: "1OxwbnwmvMoJB", title: "MEDIA ETHICS | CREATOR REVENUE | CLIPPING GAME", poster: "/broadcasts/replay-card.svg", date: "2026-08-17", sourceUrl: "https://x.com/i/broadcasts/1OxwbnwmvMoJB" },
  { id: "video-broadcast-2026-08-15-01", title: "PODCAST DRAMA | GILBERT ARENAS QUITS | DRAKE'S NEW ALBUM", poster: "/broadcasts/replay-card.svg", date: "2026-08-15", sourceUrl: null },
  { id: "1jxXgBBneeEJZ", title: "MIKO GRIMES LIVE | RELATIONSHIPS & PODCAST MONEY | LAKERS SALE", poster: "/broadcasts/replay-card.svg", date: "2026-08-14", sourceUrl: "https://x.com/i/broadcasts/1jxXgBBneeEJZ" },
  { id: "1vKpPNPWnnbKE", title: "CREATOR BREAKUP | DOXXING & LAWSUITS | SETTING BOUNDARIES", poster: "/broadcasts/replay-card.svg", date: "2026-08-12", sourceUrl: "https://x.com/i/broadcasts/1vKpPNPWnnbKE" },
  { id: "1OxwbnlaZpqJB", title: "BACK-CHANNEL BEEF | BRAY & MONA | J. COLE DISCOURSE", poster: "/broadcasts/replay-card.svg", date: "2026-08-10", sourceUrl: "https://x.com/i/broadcasts/1OxwbnlaZpqJB" },
  { id: "1OGwbbdYvObKB", title: "FRIDAY VIBES | WHO POPPED: THE JBP MYSTERY | DAME DASH", poster: "/broadcasts/replay-card.svg", date: "2026-08-07", sourceUrl: "https://x.com/i/broadcasts/1OGwbbdYvObKB" },
  { id: "1YxNrrlymkVxw", title: "ANONS & CLIP-CRAZY ENERGY | THE MADDIE LOOP | DUMBO BOUNDARY", poster: "/broadcasts/replay-card.svg", date: "2026-08-07", sourceUrl: "https://x.com/i/spaces/1YxNrrlymkVxw" },
  { id: "audio-space-2026-08-05-02", title: "MORNING SPACE | OUTWORKING THE POD | 52-VIDEO MONTH", poster: "/broadcasts/replay-card.svg", date: "2026-08-05", sourceUrl: null },
  { id: "audio-space-2026-08-05-01", title: "LATE NIGHT SPACE | MEG & TORY FALLOUT | JAMAICA RETREAT", poster: "/broadcasts/replay-card.svg", date: "2026-08-05", sourceUrl: null },
  { id: "1kJzDDYMPZXKv", title: "MONDAY RESET | THE ATTENTION ECONOMY | BUILDING A MEDIA OP", poster: "/broadcasts/replay-card.svg", date: "2026-08-03", sourceUrl: "https://x.com/i/broadcasts/1kJzDDYMPZXKv" },
  { id: "1pKdRRkyMONJW", title: "FRIDAY LIVE | JBP CAST DEBATE | DJ ENVY HYGIENE", poster: "/broadcasts/replay-card.svg", date: "2026-07-31", sourceUrl: "https://x.com/i/broadcasts/1pKdRRkyMONJW" },
  { id: "audio-space-2026-07-30-02", title: "THE NOLAN WELLS CASE | CALLING MISSISSIPPI | SUNDOWN TOWNS", poster: "/broadcasts/replay-card.svg", date: "2026-07-30", sourceUrl: null },
  { id: "audio-space-2026-07-30-01", title: "JIM JONES DEBATE | 38 SPESH | MAX B", poster: "/broadcasts/replay-card.svg", date: "2026-07-30", sourceUrl: null },
  { id: "1AKEmmrYnnnKL", title: "CAN'T DUB ME RADIO: ROC SOLID | KAREN CIVIL | WE TURNING UP", poster: "/broadcasts/1AKEmmrYnnnKL.png", date: "2026-07-27", sourceUrl: "https://x.com/i/broadcasts/1AKEmmrYnnnKL" },
  { id: "video-broadcast-2026-07-26-01", title: "YG VS GAME | LEBRON'S LAST DECISION | LA CULTURE", poster: "/broadcasts/replay-card.svg", date: "2026-07-26", sourceUrl: null },
  { id: "1rGmqqargvLGy", title: "FRIDAY FUNK | THEY STINK WITH MESS | VIBES ONLY", poster: "/broadcasts/1rGmqqargvLGy.jpg", date: "2026-07-24", sourceUrl: "https://x.com/i/broadcasts/1rGmqqargvLGy" },
  { id: "1jGXggPZWLVKZ", title: "RORY WAS HATIN | Live Broadcast", poster: "/broadcasts/1jGXggPZWLVKZ.jpg", date: "2026-07-22", sourceUrl: "https://x.com/i/broadcasts/1jGXggPZWLVKZ" },
  { id: "1YGNrrmoqZoGw", title: "STARTING THE WEEK OFF RIGHT PT 2 | TURN UP", poster: "/broadcasts/1YGNrrmoqZoGw.jpg", date: "2026-07-20", sourceUrl: "https://x.com/i/broadcasts/1YGNrrmoqZoGw" },
  { id: "1XxyggRVnEVGM", title: "EXTENDED MESSY LIVE | SPACE WARS & VIBES", poster: "/broadcasts/1XxyggRVnEVGM.jpg", date: "2026-07-18", sourceUrl: "https://x.com/i/broadcasts/1XxyggRVnEVGM" },
  { id: "1AxRnnwoqwyxl", title: "It's Friday!!!! Whewww Lots to Talk About!!!", poster: "/broadcasts/1AxRnnwoqwyxl.jpg", date: "2026-07-17", sourceUrl: "https://x.com/i/broadcasts/1AxRnnwoqwyxl" },
  { id: "1nxeLLQwQjoJX", title: "MEDIA STREETS ON FIRE!!! LOTS OF FILES", poster: "/broadcasts/1nxeLLQwQjoJX.jpg", date: "2026-07-10", sourceUrl: "https://x.com/i/broadcasts/1nxeLLQwQjoJX" },
  { id: "1dJrPPLmBlqKX", title: "BREAKFAST CLUB DEBATE | CREATOR DEALS | STREAMER DRAMA", poster: "/broadcasts/replay-card.svg", date: "2026-07-06", sourceUrl: "https://x.com/i/broadcasts/1dJrPPLmBlqKX" },
  { id: "1DxLddryWQPxm", title: "4TH of July SPECIAL | WAKE IT UP!!!!!", poster: "/broadcasts/1DxLddryWQPxm.jpg", date: "2026-07-04", sourceUrl: "https://x.com/i/broadcasts/1DxLddryWQPxm" },
  { id: "1vJpPPOnjPZJE", title: "CREATOR LABOR | CLIPPING WORKFLOW | MAYWEATHER ALLEGATIONS", poster: "/broadcasts/replay-card.svg", date: "2026-07-03", sourceUrl: "https://x.com/i/broadcasts/1vJpPPOnjPZJE" },
  { id: "1XxyggYqmoeGM", title: "JOE BUDDEN NEW WEBAPP | SATURDAY VIBES | BONUS CONTENT", poster: "/broadcasts/1XxyggYqmoeGM.jpg", date: "2026-06-27", sourceUrl: "https://x.com/i/broadcasts/1XxyggYqmoeGM" },
  { id: "1qKVmmLLaydxB", title: "SPONSORSHIPS & CONFLICT | CREATOR REVENUE | GATEKEEPING", poster: "/broadcasts/replay-card.svg", date: "2026-06-26", sourceUrl: "https://x.com/i/broadcasts/1qKVmmLLaydxB" },
  { id: "1pKdRRlAvRjJW", title: "R&B BEYOND STREAMING | PRODUCER LAWSUIT | URBAN PODCASTING", poster: "/broadcasts/replay-card.svg", date: "2026-06-19", sourceUrl: "https://x.com/i/broadcasts/1pKdRRlAvRjJW" },
  { id: "1jGXggZlkdVKZ", title: "NYC | AKADEMIKS SCARED NOW? | JOE BUDDEN VS MOUSE JONES", poster: "/broadcasts/1jGXggZlkdVKZ.jpg", date: "2026-06-15", sourceUrl: "https://x.com/i/broadcasts/1jGXggZlkdVKZ" },
  { id: "1YxNrrOVnryxw", title: "CANNABIS & CREATOR BUSINESS | $20K DISPUTE | PRODUCER LAWSUIT", poster: "/broadcasts/replay-card.svg", date: "2026-06-13", sourceUrl: "https://x.com/i/broadcasts/1YxNrrOVnryxw" },
  { id: "1PKqrrqvyomGb", title: "PODCAST PANEL POLITICS | PATREON DECLINE | PRISON SURVIVAL", poster: "/broadcasts/replay-card.svg", date: "2026-06-12", sourceUrl: "https://x.com/i/broadcasts/1PKqrrqvyomGb" },
  { id: "1mGPaawEbrMJN", title: "MEDIA BEEF | BUY BACK THE BLOCK | MUSIC CATALOGS", poster: "/broadcasts/replay-card.svg", date: "2026-06-02", sourceUrl: "https://x.com/i/broadcasts/1mGPaawEbrMJN" },
  { id: "1yNGabgjOOdJj", title: "KENDRICK'S GRAMMY | FAME & COMMUNITY | INDIE JOURNALISM", poster: "/broadcasts/replay-card.svg", date: "2026-02-02", sourceUrl: "https://x.com/i/broadcasts/1yNGabgjOOdJj" },
  { id: "1gqxvrQPDrexB", title: "50 CENT CONTRACT DRAMA | RAY J HEALTH SCARE | SAYO'S PODCAST", poster: "/broadcasts/replay-card.svg", date: "2026-01-28", sourceUrl: "https://x.com/i/broadcasts/1gqxvrQPDrexB" },
  { id: "1PlKQOpPnLBJE", title: "SPACES NEED TOPICS | STALE PODCAST FORMATS | PAID CRITICS", poster: "/broadcasts/replay-card.svg", date: "2026-01-26", sourceUrl: "https://x.com/i/broadcasts/1PlKQOpPnLBJE" },
  { id: "1lPJqvXORAExb", title: "RAP BEEF AS MARKETING | PUBLISHING RIGHTS | VIRAL LEGAL CLAIMS", poster: "/broadcasts/replay-card.svg", date: "2026-01-16", sourceUrl: "https://x.com/i/broadcasts/1lPJqvXORAExb" },
  { id: "1OyJAjEEroDxb", title: "INSIDE A JAIL POD | ROCKY'S MESSAGES | THE DANNY STORY", poster: "/broadcasts/replay-card.svg", date: "2026-01-15", sourceUrl: "https://x.com/i/broadcasts/1OyJAjEEroDxb" },
  { id: "1LyxBXdyVPrGN", title: "PODCAST CHEMISTRY | CREATOR BUSINESS | INDIE MEDIA", poster: "/broadcasts/replay-card.svg", date: "2026-01-14", sourceUrl: "https://x.com/i/broadcasts/1LyxBXdyVPrGN" },
  { id: "1ZkJzZmNeeWJv", title: "J. COLE REFUSES THE BEEF | PODCAST ECONOMICS | TRUMP MEME COIN", poster: "/broadcasts/replay-card.svg", date: "2026-01-08", sourceUrl: "https://x.com/i/broadcasts/1ZkJzZmNeeWJv" },
  { id: "1MYGNlPQYvvxw", title: "CHRISTMAS EVE LIVE | NICKI'S POLITICAL TURN | MAX B ALBUM", poster: "/broadcasts/replay-card.svg", date: "2025-12-24", sourceUrl: "https://x.com/i/broadcasts/1MYGNlPQYvvxw" },
  { id: "1zqKVdEyYOLJB", title: "WHO CLAIMS HIP-HOP? | GHOSTFACE & 'PAUSE' | LUIGI CASE", poster: "/broadcasts/replay-card.svg", date: "2025-12-23", sourceUrl: "https://x.com/i/broadcasts/1zqKVdEyYOLJB" },
  { id: "1ZkKzZkYPlLKv", title: "BLACK HOWARD STERN? | VIDEO PODCAST WARS | IF 40% COLLAPSE", poster: "/broadcasts/replay-card.svg", date: "2025-12-16", sourceUrl: "https://x.com/i/broadcasts/1ZkKzZkYPlLKv" },
];
// ---- END GENERATED ----

/**
 * Display label for a broadcast. Uses the Broadcast Titles tab title when one
 * exists; otherwise a factual date-based label ("X Broadcast — August 26, 2026")
 * so the page never renders empty headings. This is a descriptor, not a title —
 * real titles still come only from the sheet and blanks still fail the sync.
 */
const MONTH_NAMES = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

export function displayTitleFor(broadcast: XBroadcast): string {
  const real = broadcast.title?.trim();
  if (real) return real;
  const m = broadcast.date?.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (m) {
    const month = MONTH_NAMES[Number(m[2]) - 1] ?? m[2];
    return `X Broadcast — ${month} ${Number(m[3])}, ${m[1]}`;
  }
  return "X Broadcast Replay";
}

export function extractReplayHlsUrl(html: string): string | null {
  const normalized = html
    .replaceAll("\\u0026", "&")
    .replaceAll("\\/", "/")
    .replaceAll("&amp;", "&");
  const matches = normalized.match(/https:\/\/[^"'<>\s]+\.m3u8(?:\?[^"'<>\s]*)?/g) ?? [];
  return matches.find(url => url.includes("periscope-replay") || url.includes("type=replay")) ?? matches[0] ?? null;
}
