export type XBroadcast = {
  id: string;
  title: string;
  poster: string;
};

export type XBroadcastReplay = XBroadcast & {
  hlsUrl: string | null;
};

// ---- GENERATED by `npm run broadcasts:sync` — do not hand-edit ----
export const xBroadcasts: XBroadcast[] = [
  { id: "1DxLdZjlmrQxm", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1DxLdZjQNOaxm", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1NGaroPyqNnJj", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1AKEmvMgaRkKL", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1RKjpbVMRvLJw", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1lKQRWkMVwVGE", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1AxRnZXRdPqxl", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1nxeLMYVXwoJX", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1MJgNbrPzoqGL", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1PKqrNAvXEbGb", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1oKMvNLVMzNGQ", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1kJzDPoaOpRKv", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1oKMvNOXBpnGQ", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1DxleVDmnWgKL", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1jxXgBzgylvJZ", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1OxwbnwmvMoJB", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "video-broadcast-2026-08-15-01", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1jxXgBBneeEJZ", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1vKpPNPWnnbKE", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1OxwbnlaZpqJB", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1OGwbbdYvObKB", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1YxNrrlymkVxw", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "audio-space-2026-08-05-02", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "audio-space-2026-08-05-01", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1kJzDDYMPZXKv", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1pKdRRkyMONJW", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "audio-space-2026-07-30-02", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "audio-space-2026-07-30-01", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1AKEmmrYnnnKL", title: "CAN'T DUB ME RADIO: ROC SOLID | KAREN CIVIL | WE TURNING UP", poster: "/broadcasts/1AKEmmrYnnnKL.png" },
  { id: "video-broadcast-2026-07-26-01", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1rGmqqargvLGy", title: "FRIDAY FUNK | THEY STINK WITH MESS | VIBES ONLY", poster: "/broadcasts/1rGmqqargvLGy.jpg" },
  { id: "1jGXggPZWLVKZ", title: "RORY WAS HATIN | Live Broadcast", poster: "/broadcasts/1jGXggPZWLVKZ.jpg" },
  { id: "1YGNrrmoqZoGw", title: "STARTING THE WEEK OFF RIGHT PT 2 | TURN UP", poster: "/broadcasts/1YGNrrmoqZoGw.jpg" },
  { id: "1XxyggRVnEVGM", title: "EXTENDED MESSY LIVE | SPACE WARS & VIBES", poster: "/broadcasts/1XxyggRVnEVGM.jpg" },
  { id: "1AxRnnwoqwyxl", title: "It's Friday!!!! Whewww Lots to Talk About!!!", poster: "/broadcasts/1AxRnnwoqwyxl.jpg" },
  { id: "1nxeLLQwQjoJX", title: "MEDIA STREETS ON FIRE!!! LOTS OF FILES", poster: "/broadcasts/1nxeLLQwQjoJX.jpg" },
  { id: "1dJrPPLmBlqKX", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1DxLddryWQPxm", title: "4TH of July SPECIAL | WAKE IT UP!!!!!", poster: "/broadcasts/1DxLddryWQPxm.jpg" },
  { id: "1vJpPPOnjPZJE", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1XxyggYqmoeGM", title: "JOE BUDDEN NEW WEBAPP | SATURDAY VIBES | BONUS CONTENT", poster: "/broadcasts/1XxyggYqmoeGM.jpg" },
  { id: "1qKVmmLLaydxB", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1pKdRRlAvRjJW", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1jGXggZlkdVKZ", title: "NYC | AKADEMIKS SCARED NOW? | JOE BUDDEN VS MOUSE JONES", poster: "/broadcasts/1jGXggZlkdVKZ.jpg" },
  { id: "1YxNrrOVnryxw", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1PKqrrqvyomGb", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1mGPaawEbrMJN", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1yNGabgjOOdJj", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1gqxvrQPDrexB", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1PlKQOpPnLBJE", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1lPJqvXORAExb", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1OyJAjEEroDxb", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1LyxBXdyVPrGN", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1ZkJzZmNeeWJv", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1MYGNlPQYvvxw", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1zqKVdEyYOLJB", title: "", poster: "/broadcasts/placeholder.svg" },
  { id: "1ZkKzZkYPlLKv", title: "", poster: "/broadcasts/placeholder.svg" },
];
// ---- END GENERATED ----

export function extractReplayHlsUrl(html: string): string | null {
  const normalized = html
    .replaceAll("\\u0026", "&")
    .replaceAll("\\/", "/")
    .replaceAll("&amp;", "&");
  const matches = normalized.match(/https:\/\/[^"'<>\s]+\.m3u8(?:\?[^"'<>\s]*)?/g) ?? [];
  return matches.find(url => url.includes("periscope-replay") || url.includes("type=replay")) ?? matches[0] ?? null;
}
