#!/usr/bin/env node
/**
 * broadcasts:sync — regenerate app/lib/x-broadcasts.ts from the
 * Dub Clip Library master sheet instead of hand-editing the list.
 *
 * Reads:
 *   - "Master Library" tab: one site entry per distinct Episode key (col K).
 *     id    = X broadcast ID parsed from col I (Source broadcast URL),
 *             falling back to the episode key when unparseable.
 *   - "Broadcast Titles" tab: col A = episode key, col B = broadcast-level title.
 *     Episodes with no title are reported and left blank — titles are never invented.
 *     Each entry also carries the episode date (key-embedded YYYY-MM-DD, else
 *     Master Library col A) so the site can render a factual date-based display
 *     label instead of an empty heading while titles stay blank.
 *   - public/broadcasts/<id>.png|.jpg for poster art; episodes without a poster
 *     file use PLACEHOLDER_POSTER (never a broken path).
 *
 * Writes: app/lib/x-broadcasts.ts (only the marked GENERATED region; the
 * extractReplayHlsUrl helper and types below it are preserved).
 *
 * Auth: uses the `hatch_gws_cli` already configured in this environment.
 * No sheet credentials are stored in the repo.
 *
 * Exits non-zero when any episode is missing a title, so blank titles
 * can't ship silently — fill them in on the "Broadcast Titles" tab and re-run.
 */
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const MASTER_SHEET_ID =
  process.env.CLIP_LIBRARY_SHEET_ID ?? "17uhDO06vmVEz96YrUnA6aHyV5fL_3AAs3ylOjrYRLwI";
const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const TARGET_FILE = join(REPO_ROOT, "app", "lib", "x-broadcasts.ts");
const POSTERS_DIR = join(REPO_ROOT, "public", "broadcasts");
const PLACEHOLDER_POSTER = "/broadcasts/placeholder.svg";

const GENERATED_BEGIN = "// ---- GENERATED by `npm run broadcasts:sync` — do not hand-edit ----";
const GENERATED_END = "// ---- END GENERATED ----";

// Matches https://x.com/i/broadcasts/<id> and https://x.com/i/spaces/<id>.
// Status URLs (/thefileswithdub/status/<id>) are NOT broadcast IDs.
const BROADCAST_ID_RE = /\/(?:broadcasts|spaces)\/([A-Za-z0-9_-]+)/;

function sheetValues(range) {
  const out = execFileSync(
    "hatch_gws_cli",
    [
      "sheets", "spreadsheets", "values", "get",
      "--params", JSON.stringify({ spreadsheetId: MASTER_SHEET_ID, range, fields: "values" }),
    ],
    { encoding: "utf8", stdio: ["ignore", "pipe", "inherit"] },
  );
  return JSON.parse(out).values ?? [];
}

function parseBroadcastId(url) {
  if (!url) return null;
  const clean = String(url).split(/[?#]/)[0];
  const m = clean.match(BROADCAST_ID_RE);
  return m ? m[1] : null;
}

function posterFor(id) {
  for (const ext of ["png", "jpg"]) {
    if (existsSync(join(POSTERS_DIR, `${id}.${ext}`))) return `/broadcasts/${id}.${ext}`;
  }
  return PLACEHOLDER_POSTER;
}

function tsString(value) {
  return JSON.stringify(value);
}

// --- Read the sheet -------------------------------------------------------
const masterRows = sheetValues("Master Library!A1:K").slice(1); // drop header
const titleRows = sheetValues("Broadcast Titles!A1:B").slice(1); // drop header
const titles = new Map(
  titleRows.filter(r => r[0]?.trim()).map(r => [r[0].trim(), (r[1] ?? "").trim()]),
);

// Group clip rows by episode key (col K, index 10).
const episodes = new Map();
for (const row of masterRows) {
  const key = (row[10] ?? "").trim();
  if (!key) continue;
  if (!episodes.has(key)) episodes.set(key, { key, date: row[0] ?? "", urls: [] });
  const url = (row[8] ?? "").trim();
  if (url) episodes.get(key).urls.push(url);
}

// --- Build entries ---------------------------------------------------------
const entries = [];
const missingTitles = [];
const seenIds = new Map();
const duplicateIds = [];
for (const ep of episodes.values()) {
  let id = null;
  for (const url of ep.urls) {
    id = parseBroadcastId(url);
    if (id) break;
  }
  if (!id) id = ep.key; // fallback per spec
  if (seenIds.has(id)) duplicateIds.push(`${id} (${seenIds.get(id)} vs ${ep.key})`);
  else seenIds.set(id, ep.key);

  const title = titles.get(ep.key) ?? "";
  if (!title) missingTitles.push(ep.key);
  // Factual date for display fallbacks (never invents a title): prefer the
  // YYYY-MM-DD embedded in the episode key, else the Master Library date col.
  const keyDate = episodeDate(ep.key);
  const colDate = String(ep.date ?? "").match(/(\d{4})-(\d{2})-(\d{2})/);
  const date = keyDate || (colDate ? `${colDate[1]}-${colDate[2]}-${colDate[3]}` : "");
  entries.push({ id, title, poster: posterFor(id), date, key: ep.key });
}

// Newest episode first. Keys embed YYYY-MM-DD, so sort by date desc, then key.
function episodeDate(key) {
  const m = key.match(/(\d{4}-\d{2}-\d{2})/);
  return m ? m[1] : "";
}
entries.sort((a, b) =>
  episodeDate(b.key).localeCompare(episodeDate(a.key)) || b.key.localeCompare(a.key),
);

// --- Render the generated region -------------------------------------------
const lines = entries.map(
  e => `  { id: ${tsString(e.id)}, title: ${tsString(e.title)}, poster: ${tsString(e.poster)}, date: ${tsString(e.date)} },`,
);
const generated = [
  GENERATED_BEGIN,
  "export const xBroadcasts: XBroadcast[] = [",
  ...lines,
  "];",
  GENERATED_END,
].join("\n");

// --- Splice into the target file, preserving everything else ---------------
let source = readFileSync(TARGET_FILE, "utf8");
const beginIdx = source.indexOf(GENERATED_BEGIN);
if (beginIdx !== -1) {
  const endIdx = source.indexOf(GENERATED_END, beginIdx);
  if (endIdx === -1) throw new Error("GENERATED begin marker without end marker");
  source =
    source.slice(0, beginIdx) +
    generated +
    source.slice(endIdx + GENERATED_END.length);
} else {
  // First run: replace the hand-written array literal.
  const replaced = source.replace(
    /export const xBroadcasts: XBroadcast\[\] = \[[\s\S]*?\];/,
    generated,
  );
  if (replaced === source) throw new Error("could not locate xBroadcasts array to replace");
  source = replaced;
}
writeFileSync(TARGET_FILE, source.replace(/(---- END GENERATED ----)\n{3,}/, "$1\n\n"));

// --- Report -----------------------------------------------------------------
const withPosters = entries.filter(e => e.poster !== PLACEHOLDER_POSTER).length;
console.log(`synced ${entries.length} episodes from ${masterRows.length} clip rows`);
console.log(`posters: ${withPosters} matched, ${entries.length - withPosters} placeholder`);
if (duplicateIds.length) {
  console.warn("WARNING: duplicate broadcast ids:");
  for (const d of duplicateIds) console.warn(`  - ${d}`);
}
// Orphan poster files: present on disk but referenced by no entry.
const referenced = new Set(entries.map(e => e.poster));
const orphans = readdirSync(POSTERS_DIR)
  .filter(f => /^\.(png|jpg)$/.test(f.slice(-4)) || /\.(png|jpg)$/.test(f))
  .filter(f => !referenced.has(`/broadcasts/${f}`) && f !== "placeholder.svg");
if (orphans.length) {
  console.warn("WARNING: poster files with no matching episode (kept on disk):");
  for (const o of orphans) console.warn(`  - ${o}`);
}
if (missingTitles.length) {
  console.warn(`WARNING: ${missingTitles.length} episodes have no title on the "Broadcast Titles" tab (left blank, not invented):`);
  for (const k of missingTitles) console.warn(`  - ${k}`);
  process.exitCode = 1;
}
console.log(`wrote ${TARGET_FILE}`);
